server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # override 활성
  main:
    allow-bean-definition-overriding: true
  # driver
  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost:9092/mem:testdb2
      driver-class-name: org.h2.Driver
      username: sa
      password:
  # spring Data JPA
  jpa:
    database-platform: H2
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  # driver - connect client
  h2:
    console:
      enabled: true
      path: /h2-console
