server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  # driver - connect client
  h2:
    console:
      enabled: true
      path: /h2-console
  # driver
  datasource:
    hikari:
      #jdbc-url: # ? ? ?
      driver-class-name: org.h2.Driver
      username: sa
      password:
    continue-on-error: true

  # spring Data JPA
  jpa:
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      show-sql: true
