INSERT INTO USER (USERNBR, USERNAME, PASSWORD, ROLES)
VALUES (1, 'jane', '1234', 'ADMIN');

INSERT INTO USER (USERNBR, USERNAME, PASSWORD, ROLES)
VALUES (2, 'admin', '1234', 'ADMIN');

INSERT INTO USER (USERNBR, USERNAME, PASSWORD, ROLES)
VALUES (3, 'manager', '1234', 'MANAGER');

INSERT INTO USER (USERNBR, USERNAME, PASSWORD, ROLES)
VALUES (4, 'user', '1234', 'USER');